version: '3.8'

services:
  nginx_debakel:
    image: nginx:mainline-alpine
    container_name: debakel_web
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    networks:
      - debakel
    ports:
      - 8081:80
    environment:
      - TZ=Europe/Vienna

networks:
  debakel:
    name: debakel
